import { NextPage } from 'next'
import Head from 'next/head'

interface Props {
  message: string
}
const Home: NextPage<Props> = ({ message }) => {
  console.log(message)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hello World
      </div>
    </div>
  )
}

export default Home;

Home.getInitialProps = async (ctx) => {
  const res = await fetch('http://localhost:4000/api/v1')
  const json = await res.json();
  return {
    message: json.message
  }
}
